import { createSlice, type PayloadAction } from '@reduxjs/toolkit';

/**
 * `signup` global store (CLAUDE.md §8) — transient state for the multi-step signup flow.
 * `sessionId` is generated by POST /auth/signup/initiate and reused by verify-otp and onboard.
 */
export interface SignupState {
  sessionId: string | null;
  email: string | null;
  mobile: string | null;
}

const initialState: SignupState = { sessionId: null, email: null, mobile: null };

const signupSlice = createSlice({
  name: 'signup',
  initialState,
  reducers: {
    signupInitiated(state, action: PayloadAction<{ sessionId: string; email?: string; mobile?: string }>) {
      state.sessionId = action.payload.sessionId;
      state.email = action.payload.email ?? null;
      state.mobile = action.payload.mobile ?? null;
    },
    clearSignup() {
      return initialState;
    },
  },
});

export const { signupInitiated, clearSignup } = signupSlice.actions;
export const signupReducer = signupSlice.reducer;

export interface WithSignup {
  signup: SignupState;
}
export const selectSignupSessionId = (s: WithSignup): string | null => s.signup.sessionId;
