import { meSchema, type Me } from './model/meSchema';

/**
 * DEV-ONLY mock of the GET /me response payload. Backend is not ready yet; this is the exact
 * shape the API will return (validated through `meSchema`). Replace the loader's source with the
 * real `getMe` query when the endpoint exists — the store shape stays the same.
 */
const RAW_ME = {
  user: { id: '56699892-a14b-4ff8-ad3e-48fc3932c2a6', username: '653410', status: 'ACTIVE' },
  roles: ['ADMIN'],
  permissions: [
    'AUDIT.VIEW',
    'BRANCH.CREATE',
    'BRANCH.DELETE',
    'BRANCH.EDIT',
    'BRANCH.VIEW',
    'CUSTOMER.CREATE',
    'CUSTOMER.DELETE',
    'CUSTOMER.EDIT',
    'CUSTOMER.VIEW',
    'DOC_CONFIG.EDIT',
    'DOC_CONFIG.VIEW',
    'DOCUMENT.APPROVE',
    'DOCUMENT.CANCEL',
    'DOCUMENT.CREATE',
    'DOCUMENT.DELETE',
    'DOCUMENT.EDIT',
    'DOCUMENT.EXPORT',
    'DOCUMENT.PRINT',
    'DOCUMENT.VIEW',
    'EMPLOYEE.ASSIGN_ROLE',
    'EMPLOYEE.CREATE',
    'EMPLOYEE.DEACTIVATE',
    'EMPLOYEE.EDIT',
    'EMPLOYEE.RESET_PASSWORD',
    'EMPLOYEE.VIEW',
    'INVENTORY.ADJUST',
    'INVENTORY.TRANSFER',
    'INVENTORY.VIEW',
    'LEGAL_ENTITY.CREATE',
    'LEGAL_ENTITY.DELETE',
    'LEGAL_ENTITY.EDIT',
    'LEGAL_ENTITY.VIEW',
    'ORG.EDIT',
    'ORG.VIEW',
    'PRODUCT.CREATE',
    'PRODUCT.DELETE',
    'PRODUCT.EDIT',
    'PRODUCT.VIEW',
    'REPORT.EXPORT',
    'REPORT.FINANCIAL',
    'REPORT.GST',
    'REPORT.INVENTORY',
    'REPORT.PURCHASE',
    'REPORT.SALES',
    'ROLE.CREATE',
    'ROLE.DELETE',
    'ROLE.EDIT',
    'ROLE.MANAGE_PERMISSIONS',
    'ROLE.VIEW',
    'SETTINGS.EDIT',
    'SETTINGS.VIEW',
    'SUPPLIER.CREATE',
    'SUPPLIER.DELETE',
    'SUPPLIER.EDIT',
    'SUPPLIER.VIEW',
    'TAX.MANAGE',
    'TAX.VIEW',
    'UOM.MANAGE',
    'UOM.VIEW',
  ],
  tenant: { id: '55f1e65a-0c52-45f4-ba5f-696d6daa587f', name: 'Acme Traders' },
  business: {
    id: '92933702-0549-4cf7-9b82-f31f60cd3e7b',
    tenantId: '55f1e65a-0c52-45f4-ba5f-696d6daa587f',
    name: 'Acme Traders',
    businessType: null,
    sector: null,
    status: 'PENDING_ONBOARDING',
  },
  employee: {
    id: '5ea4729a-c5a2-4a34-9a96-c8cd1579d4e9',
    firstName: 'Jane',
    lastName: 'Doe',
    email: 'jane.doe+7091265@example.com',
    mobile: '9007091265',
    status: 'RESET_PENDING',
  },
  legalEntities: [
    {
      id: '5c2ee870-a732-4ff5-a9d4-f68bc390901a',
      legalName: 'Acme Traders Pvt Ltd',
      entityType: 'PRIVATE_LIMITED',
      gstin: '27ABCDE1234F1Z5',
      city: 'Pune',
      state: 'Maharashtra',
      isPrimary: true,
      status: 'ACTIVE',
    },
  ],
  storageUnits: [
    {
      id: '2f7b9070-6e65-437e-9725-271441045f8e',
      name: 'Main Warehouse',
      type: 'WAREHOUSE',
      city: 'Pune',
      isDefault: true,
      status: 'ACTIVE',
    },
  ],
};

/** Parsed + validated mock — mirrors `meSchema.parse(response.data)` against the real API. */
export const DEV_ME: Me = meSchema.parse(RAW_ME);
